### PR TITLE
Golang style result

### PR DESCRIPTION
**Pull request by thelinuxlich**
I liked your library but made some changes so it returns a result tuple, similar to Golang style of dealing with exceptions. See if you like, if not I will rename my implementation, mentioning your project.

### CODE REVIEW

**Comment by astoilkov** [comment]
I like the idea. I might adopt it. I would probably swap the value and the error `const [value, error] = goodTry()`. Otherwise, from first sight, I think your idea is superior.

Thanks!

**Comment by thelinuxlich** [comment]
the err is first because we are used to the err as the first parameter in node.js callbacks, also, it stimulates a data-last approach

**Comment by thelinuxlich** [comment]
Other things I've changed:

- err and value can be undefined, not null (enforce good practices)
- default value should be the same type as the expected returned value from the function (consistency)
- removed the callback to deal with errors, also the function resolving to promise

**Comment by astoilkov** [comment]
I did this in https://github.com/astoilkov/settle-it package instead of here. I will update the docs of good-try and point all people to settle-it as it covers all cases and it's the better API. Thanks for the idea!

**Pull request closed without merging**
